[package]
name = "ca-certificates"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://curl.se/docs/caextract.html"
