[workspace]
members = [
    "api/apiserver",
    "api/apiclient",
    "api/bootstrap-containers",
    "api/bork",
    "api/certdog",
    "api/corndog",
    "api/datastore",
    "api/early-boot-config",
    "api/ecs-settings-applier",
    "api/netdog",
    "api/sundog",
    "api/schnauzer",
    "api/pluto",
    "api/host-containers",
    "api/static-pods",
    "api/storewolf",
    "api/thar-be-settings",
    "api/thar-be-updates",
    "api/settings-committer",
    "api/migration/migrator",
    "api/migration/migration-helpers",
    "api/shibaken",
    "api/prairiedog",

    # "api/migration/migrations/vX.Y.Z/..."
    "api/migration/migrations/v1.10.1/container-runtime",
    "api/migration/migrations/v1.10.1/container-runtime-metadata",
    "api/migration/migrations/v1.11.0/aws-creds",
    "api/migration/migrations/v1.11.0/aws-creds-metadata",
    "api/migration/migrations/v1.11.0/aws-config-settings",
    "api/migration/migrations/v1.11.0/credential-providers",
    "api/migration/migrations/v1.11.0/kubelet-tls-config",
    "api/migration/migrations/v1.11.0/kubelet-tls-files",
    "api/migration/migrations/v1.11.0/kubelet-new-config-files",
    "api/migration/migrations/v1.11.0/ecs-additional-configurations",
    "api/migration/migrations/v1.11.0/aws-admin-container-v0-9-3",
    "api/migration/migrations/v1.11.0/public-admin-container-v0-9-3",
    "api/migration/migrations/v1.11.0/aws-control-container-v0-6-4",
    "api/migration/migrations/v1.11.0/public-control-container-v0-6-4",

    "bottlerocket-release",

    "bottlerocket-variant",

    "imdsclient",

    "driverdog",

    "generate-readme",

    "ghostdog",

    "metricdog",

    "cfsignal",

    "logdog",

    "models",

    "parse-datetime",

    "retry-read",

    "updater/block-party",
    "updater/signpost",
    "updater/update_metadata",
    "updater/updog",

    "constants",

    "shimpei"
]

[profile.release]
debug = true
