[package]
name = "docker-cli"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/docker/cli/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/docker/cli/archive/v20.10.20/cli-20.10.20.tar.gz"
sha512 = "536c26b421fb0ca92a09ff67f4fa3afd64115ef9f748ae7fb6d3448c4c1acade72bef037f71017e9c3e039ecada95fb157d9f336ee3348be1f21874730bcb03e"

[build-dependencies]
glibc = { path = "../glibc" }
